import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { URL } from 'node:url'
import { test } from 'bun:test'

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('keeps Local a zero-external-service desktop composition with reproducible recovery', async () => {
  const manifest = JSON.parse(await read('apps/local-control-plane/package.json'))
  const composition = await read('apps/local-control-plane/src/composition.ts')
  const runbook = await read('docs/local-deployment.md')
  const forbidden = ['pg', 'redis', 'temporal', 'runtime-gateway', 'docker']
  const dependencies = Object.keys(manifest.dependencies ?? {})
    .join('\n')
    .toLowerCase()
  for (const name of forbidden) assert.doesNotMatch(dependencies, new RegExp(name))
  assert.match(composition, /externalServices: 0/)
  assert.match(composition, /SqlitePersistenceProvider/)
  assert.match(composition, /LocalRestateRuntime/)
  assert.match(composition, /FilesystemObjectStore/)
  assert.match(composition, /LOCAL_RUNTIME_TRANSPORT_MUST_BE_DIRECT/)
  assert.match(runbook, /does not require\s+Docker, PostgreSQL, Redis\/Valkey, Temporal/s)
  assert.match(runbook, /sleep\/wake/)
  assert.match(runbook, /checkpoint restore --apply/)
  assert.match(runbook, /less than 750 MiB idle RSS/)
  assert.match(runbook, /\$0\/month mandatory managed-infrastructure budget/)
})

test('hardens both Hosted profiles with replaceable providers and bounded resources', async () => {
  const compose = await read('infrastructure/compose/compose.yaml')
  const environment = await read('infrastructure/compose/.env.example')
  const runbook = await read('infrastructure/compose/README.md')
  const hosted = await read('apps/hosted-control-plane/src/index.ts')
  assert.match(compose, /profiles: \[simple\]/)
  assert.match(compose, /profiles: \[server\]/)
  assert.match(compose, /restart: unless-stopped/)
  assert.match(compose, /POSTGRES_MEMORY_LIMIT:-768M/)
  assert.match(compose, /RESTATE_MEMORY_LIMIT:-768M/)
  assert.match(environment, /HOSTED_OBJECT_STORE=filesystem/)
  assert.match(environment, /POSTGRES_MIGRATION_PASSWORD=/)
  assert.match(environment, /POSTGRES_APPLICATION_PASSWORD=/)
  assert.match(hosted, /createS3CompatibleObjectStore/)
  assert.match(hosted, /HOSTED_OBJECT_STORE_ENDPOINT_INVALID/)
  assert.match(runbook, /Cloudflare R2 works through this seam/)
  assert.match(runbook, /pg_restore --clean --if-exists/)
  assert.match(runbook, /Terminate HTTPS in a same-host reverse proxy/)
  assert.match(runbook, /Hosted Simple minimum is 1 vCPU, 1 GiB RAM/)
  assert.match(runbook, /Hosted Server minimum is 2 vCPU, 4 GiB RAM/)
  assert.match(runbook, /owned by 1000:1000/)
  assert.match(runbook, /PostgreSQL image writes as UID\/GID 70/)
  assert.match(runbook, /Restate image writes as UID\/GID 0/)
  assert.match(runbook, /keep every data directory mode 0700/)
  assert.match(runbook, /USD 10\/month for the minimum Hosted Simple class/)
  assert.match(runbook, /USD 25\/month for the minimum Hosted Server class/)
})

test('binds encrypted relay recovery and telemetry to content-safe durable identities', async () => {
  const relay = await read('docs/remote-control-relay.md')
  const operations = await read('docs/operations.md')
  const conformance = await read('tests/fixtures/m10-portability.v1.json')
  assert.match(relay, /RFC 9180 HPKE Base mode/)
  assert.match(relay, /reconnect\/redelivery/)
  assert.match(relay, /idempotency key/)
  assert.match(relay, /Rotation registers a new active public key/)
  assert.match(operations, /must not require plaintext sensitive execution content/)
  assert.match(conformance, /content-redaction-v1/)
})

test('publishes checkpoint, incident, rollback, and host-loss operator contracts', async () => {
  const packageManifest = JSON.parse(await read('package.json'))
  const checkpoint = await read('scripts/control-plane-checkpoint.mjs')
  const local = await read('docs/local-deployment.md')
  const hosted = await read('infrastructure/compose/README.md')
  assert.equal(packageManifest.scripts.checkpoint, 'bun scripts/control-plane-checkpoint.mjs')
  assert.match(checkpoint, /verified-dry-run/)
  assert.match(checkpoint, /restoreFilesystemCheckpoint/)
  assert.match(local, /forward-repair/)
  assert.match(local, /host loss/i)
  assert.match(hosted, /revoke its outbound relay registration and X25519 key/)
})

test('launches both Hosted profiles on a fresh Linux CI host', async () => {
  const workflow = await read('.github/workflows/m10-operability.yml')
  const script = await read('scripts/run-hosted-compose-acceptance.sh')
  assert.match(workflow, /bash \.\.\/\.\.\/scripts\/run-hosted-compose-acceptance\.sh/)
  assert.match(workflow, /runs-on: ubuntu-latest/)
  assert.match(script, /compose --profile simple up --build -d/)
  assert.match(script, /compose --profile server up --build -d/)
  assert.match(script, /sudo chown -R 1000:1000/)
  assert.match(script, /logs --no-color/)
  assert.match(script, /applied_migrations.*expected_migrations/s)
  assert.match(script, /current_user.*control_plane_migrator/s)
  assert.match(script, /current_user.*control_plane_app/s)
  assert.match(script, /legacy_role_upgrade_probe/)
  assert.match(script, /pg_auth_members/)
  assert.match(script, /unexpectedly accepted duplicate passwords/)
  assert.match(script, /runtime_role_must_not_create_objects/)
  assert.match(script, /compose --profile server stop restate/)
  assert.match(script, /compose --profile server up --detach --wait --wait-timeout 120 restate/)
  assert.match(script, /compose --profile server stop postgres/)
  assert.match(script, /compose --profile server up --detach --wait --wait-timeout 120 postgres/)
  assert.match(script, /write-out '%\{http_code\}'.*503/s)
  assert.equal((script.match(/test "\$server_status" = 200/g) ?? []).length, 3)
})
