import {
  ModelConnectionCreateRequestSchema,
  ModelConnectionListRequestSchema,
  ModelConnectionListResponseSchema,
  ModelConnectionResponseSchema,
  ModelConnectionRevokeRequestSchema,
  ModelDefaultsGetRequestSchema,
  ModelDefaultsResponseSchema,
  ModelDefaultsSetRequestSchema,
  ModelSelectionResolveRequestSchema,
  ModelSelectionResponseSchema,
} from '@control-plane/contracts'
import {
  CredentialCreateRequestSchema,
  CredentialGetRequestSchema,
  CredentialListRequestSchema,
  CredentialListResponseSchema,
  CredentialResponseSchema,
  CredentialRevokeRequestSchema,
  CredentialRotateRequestSchema,
  GraphDefinitionPublishRequestSchema,
  GraphDefinitionDeprecationRequestSchema,
  GraphDefinitionRevocationRequestSchema,
  GraphDefinitionResolutionRequestSchema,
  GraphDefinitionResponseSchema,
  ExecutionCancellationCommandSchema,
  ExecutionCancellationCommandResultSchema,
  InteractionResponseCommandSchema,
  InteractionResponseCommandResultSchema,
  ContextPackageResolutionRequestSchema,
  ContextPackageResolutionResponseSchema,
  ExecutionAcceptanceRequestSchema,
  ExecutionAcceptanceResponseSchema,
  ExecutionRequestValidationRequestSchema,
  ExecutionRequestValidationResponseSchema,
  ProfileResolutionRequestSchema,
  ProfileResolutionResponseSchema,
  ProjectStateInitializationRequestSchema,
  ProjectStateInitializationResponseSchema,
  ProjectStateResolutionRequestSchema,
  ProjectStateResolutionResponseSchema,
  RuntimeListRequestSchema,
  RuntimeListResponseSchema,
  ServiceAuthenticationRequestSchema,
  ServiceAuthenticationResponseSchema,
  ExternalSessionGetRequestSchema,
  ExternalSessionGetResponseSchema,
  ExternalSessionListRequestSchema,
  ExternalSessionListResponseSchema,
  RuntimeConnectionGetRequestSchema,
  RuntimeConnectionGetResponseSchema,
  RuntimeConnectionListRequestSchema,
  RuntimeConnectionListResponseSchema,
  MarketplaceCatalogRequestSchema,
  MarketplaceCatalogResponseSchema,
  MarketplaceInstallPlanRequestSchema,
  MarketplaceInstallPlanResponseSchema,
  MarketplaceInstallRequestSchema,
  MarketplaceInstallResponseSchema,
  MarketplaceInstallationGetRequestSchema,
  MarketplaceInstallationGetResponseSchema,
  MarketplaceInstallationUninstallRequestSchema,
  MarketplaceInstallationUninstallResponseSchema,
  WorkspaceAgentProfileDeprecationRequestSchema,
  WorkspaceAgentProfileGetRequestSchema,
  WorkspaceAgentProfileGetResponseSchema,
  WorkspaceAgentProfileLifecycleResponseSchema,
  WorkspaceAgentProfileListRequestSchema,
  WorkspaceAgentProfileListResponseSchema,
  WorkspaceAgentProfilePublishRequestSchema,
  WorkspaceAgentProfilePublishResponseSchema,
  WorkspaceAgentProfileRevocationRequestSchema,
  WorkspaceSkillDeprecationRequestSchema,
  WorkspaceSkillGetRequestSchema,
  WorkspaceSkillGetResponseSchema,
  WorkspaceSkillLifecycleResponseSchema,
  WorkspaceSkillListRequestSchema,
  WorkspaceSkillListResponseSchema,
  WorkspaceSkillPublishRequestSchema,
  WorkspaceSkillPublishResponseSchema,
  WorkspaceSkillRevocationRequestSchema,
} from '@control-plane/contracts'

export const ControlApiOperations = Object.freeze({
  createModelConnection: {
    operation: 'model-connections.create',
    method: 'POST',
    path: '/v1/model-connections/create',
    requestSchema: ModelConnectionCreateRequestSchema,
    responseSchema: ModelConnectionResponseSchema,
  },
  revokeModelConnection: {
    operation: 'model-connections.revoke',
    method: 'POST',
    path: '/v1/model-connections/revoke',
    requestSchema: ModelConnectionRevokeRequestSchema,
    responseSchema: ModelConnectionResponseSchema,
  },
  listModelConnections: {
    operation: 'model-connections.list',
    method: 'POST',
    path: '/v1/model-connections/list',
    requestSchema: ModelConnectionListRequestSchema,
    responseSchema: ModelConnectionListResponseSchema,
  },
  getModelDefaults: {
    operation: 'model-defaults.get',
    method: 'POST',
    path: '/v1/model-connections/defaults/get',
    requestSchema: ModelDefaultsGetRequestSchema,
    responseSchema: ModelDefaultsResponseSchema,
  },
  setModelDefaults: {
    operation: 'model-defaults.set',
    method: 'POST',
    path: '/v1/model-connections/defaults/set',
    requestSchema: ModelDefaultsSetRequestSchema,
    responseSchema: ModelDefaultsResponseSchema,
  },
  resolveModelSelection: {
    operation: 'model-selection.resolve',
    method: 'POST',
    path: '/v1/model-connections/selection/resolve',
    requestSchema: ModelSelectionResolveRequestSchema,
    responseSchema: ModelSelectionResponseSchema,
  },

  createCredential: {
    operation: 'credential.create',
    method: 'POST',
    path: '/v1/credentials/create',
    requestSchema: CredentialCreateRequestSchema,
    responseSchema: CredentialResponseSchema,
  },
  rotateCredential: {
    operation: 'credential.rotate',
    method: 'POST',
    path: '/v1/credentials/rotate',
    requestSchema: CredentialRotateRequestSchema,
    responseSchema: CredentialResponseSchema,
  },
  revokeCredential: {
    operation: 'credential.revoke',
    method: 'POST',
    path: '/v1/credentials/revoke',
    requestSchema: CredentialRevokeRequestSchema,
    responseSchema: CredentialResponseSchema,
  },
  getCredential: {
    operation: 'credential.get',
    method: 'POST',
    path: '/v1/credentials/get',
    requestSchema: CredentialGetRequestSchema,
    responseSchema: CredentialResponseSchema,
  },
  listCredentials: {
    operation: 'credential.list',
    method: 'POST',
    path: '/v1/credentials/list',
    requestSchema: CredentialListRequestSchema,
    responseSchema: CredentialListResponseSchema,
  },
  publishGraph: {
    operation: 'graph.publish',
    method: 'POST',
    path: '/v1/graphs/publish',
    requestSchema: GraphDefinitionPublishRequestSchema,
    responseSchema: GraphDefinitionResponseSchema,
  },
  deprecateGraph: {
    operation: 'graph.deprecate',
    method: 'POST',
    path: '/v1/graphs/deprecate',
    requestSchema: GraphDefinitionDeprecationRequestSchema,
    responseSchema: GraphDefinitionResponseSchema,
  },
  revokeGraph: {
    operation: 'graph.revoke',
    method: 'POST',
    path: '/v1/graphs/revoke',
    requestSchema: GraphDefinitionRevocationRequestSchema,
    responseSchema: GraphDefinitionResponseSchema,
  },
  resolveGraph: {
    operation: 'graph.resolve',
    method: 'POST',
    path: '/v1/graphs/resolve',
    requestSchema: GraphDefinitionResolutionRequestSchema,
    responseSchema: GraphDefinitionResponseSchema,
  },
  listWorkspaceSkills: {
    operation: 'catalog.skill.list',
    method: 'POST',
    path: '/v1/catalog/skills/list',
    requestSchema: WorkspaceSkillListRequestSchema,
    responseSchema: WorkspaceSkillListResponseSchema,
  },
  getWorkspaceSkill: {
    operation: 'catalog.skill.get',
    method: 'POST',
    path: '/v1/catalog/skills/get',
    requestSchema: WorkspaceSkillGetRequestSchema,
    responseSchema: WorkspaceSkillGetResponseSchema,
  },
  publishWorkspaceSkill: {
    operation: 'catalog.skill.publish',
    method: 'POST',
    path: '/v1/catalog/skills/publish',
    requestSchema: WorkspaceSkillPublishRequestSchema,
    responseSchema: WorkspaceSkillPublishResponseSchema,
  },
  deprecateWorkspaceSkill: {
    operation: 'catalog.skill.deprecate',
    method: 'POST',
    path: '/v1/catalog/skills/deprecate',
    requestSchema: WorkspaceSkillDeprecationRequestSchema,
    responseSchema: WorkspaceSkillLifecycleResponseSchema,
  },
  revokeWorkspaceSkill: {
    operation: 'catalog.skill.revoke',
    method: 'POST',
    path: '/v1/catalog/skills/revoke',
    requestSchema: WorkspaceSkillRevocationRequestSchema,
    responseSchema: WorkspaceSkillLifecycleResponseSchema,
  },
  listWorkspaceProfiles: {
    operation: 'catalog.profile.list',
    method: 'POST',
    path: '/v1/catalog/profiles/list',
    requestSchema: WorkspaceAgentProfileListRequestSchema,
    responseSchema: WorkspaceAgentProfileListResponseSchema,
  },
  getWorkspaceProfile: {
    operation: 'catalog.profile.get',
    method: 'POST',
    path: '/v1/catalog/profiles/get',
    requestSchema: WorkspaceAgentProfileGetRequestSchema,
    responseSchema: WorkspaceAgentProfileGetResponseSchema,
  },
  publishWorkspaceProfile: {
    operation: 'catalog.profile.publish',
    method: 'POST',
    path: '/v1/catalog/profiles/publish',
    requestSchema: WorkspaceAgentProfilePublishRequestSchema,
    responseSchema: WorkspaceAgentProfilePublishResponseSchema,
  },
  deprecateWorkspaceProfile: {
    operation: 'catalog.profile.deprecate',
    method: 'POST',
    path: '/v1/catalog/profiles/deprecate',
    requestSchema: WorkspaceAgentProfileDeprecationRequestSchema,
    responseSchema: WorkspaceAgentProfileLifecycleResponseSchema,
  },
  revokeWorkspaceProfile: {
    operation: 'catalog.profile.revoke',
    method: 'POST',
    path: '/v1/catalog/profiles/revoke',
    requestSchema: WorkspaceAgentProfileRevocationRequestSchema,
    responseSchema: WorkspaceAgentProfileLifecycleResponseSchema,
  },
  cancelExecution: {
    responseStatus: 202,
    operation: 'execution.cancel',
    method: 'POST',
    path: '/v1/executions/cancel',
    requestSchema: ExecutionCancellationCommandSchema,
    responseSchema: ExecutionCancellationCommandResultSchema,
  },
  respondToInteraction: {
    responseStatus: 202,
    operation: 'interaction.respond',
    method: 'POST',
    path: '/v1/interactions/respond',
    requestSchema: InteractionResponseCommandSchema,
    responseSchema: InteractionResponseCommandResultSchema,
  },
  verifyAuthentication: {
    operation: 'authentication.verify',
    method: 'POST',
    path: '/v1/authentication/verify',
    requestSchema: ServiceAuthenticationRequestSchema,
    responseSchema: ServiceAuthenticationResponseSchema,
  },
  resolveProfile: {
    operation: 'profile.resolve',
    method: 'POST',
    path: '/v1/profiles/resolve',
    requestSchema: ProfileResolutionRequestSchema,
    responseSchema: ProfileResolutionResponseSchema,
  },
  resolveProjectState: {
    operation: 'project-state.resolve',
    method: 'POST',
    path: '/v1/project-states/resolve',
    requestSchema: ProjectStateResolutionRequestSchema,
    responseSchema: ProjectStateResolutionResponseSchema,
  },
  initializeProjectState: {
    operation: 'project-state.initialize',
    method: 'POST',
    path: '/v1/project-states/initialize',
    requestSchema: ProjectStateInitializationRequestSchema,
    responseSchema: ProjectStateInitializationResponseSchema,
  },
  resolveContextPackage: {
    operation: 'context-package.resolve',
    method: 'POST',
    path: '/v1/context-packages/resolve',
    requestSchema: ContextPackageResolutionRequestSchema,
    responseSchema: ContextPackageResolutionResponseSchema,
  },
  listRuntimes: {
    operation: 'runtime.list',
    method: 'POST',
    path: '/v1/runtimes/list',
    requestSchema: RuntimeListRequestSchema,
    responseSchema: RuntimeListResponseSchema,
  },
  listRuntimeConnections: {
    operation: 'runtime-connection.list',
    method: 'POST',
    path: '/v1/runtime-connections/list',
    requestSchema: RuntimeConnectionListRequestSchema,
    responseSchema: RuntimeConnectionListResponseSchema,
  },
  getRuntimeConnection: {
    operation: 'runtime-connection.get',
    method: 'POST',
    path: '/v1/runtime-connections/get',
    requestSchema: RuntimeConnectionGetRequestSchema,
    responseSchema: RuntimeConnectionGetResponseSchema,
  },
  listExternalSessions: {
    operation: 'external-session.list',
    method: 'POST',
    path: '/v1/external-sessions/list',
    requestSchema: ExternalSessionListRequestSchema,
    responseSchema: ExternalSessionListResponseSchema,
  },
  getExternalSession: {
    operation: 'external-session.get',
    method: 'POST',
    path: '/v1/external-sessions/get',
    requestSchema: ExternalSessionGetRequestSchema,
    responseSchema: ExternalSessionGetResponseSchema,
  },
  validateExecutionRequest: {
    operation: 'execution.validate',
    method: 'POST',
    path: '/v1/executions/validate',
    requestSchema: ExecutionRequestValidationRequestSchema,
    responseSchema: ExecutionRequestValidationResponseSchema,
  },
  acceptExecution: {
    operation: 'execution.accept',
    method: 'POST',
    path: '/v1/executions/accept',
    requestSchema: ExecutionAcceptanceRequestSchema,
    responseSchema: ExecutionAcceptanceResponseSchema,
  },
  marketplaceCatalog: {
    operation: 'marketplace.catalog.read',
    method: 'POST',
    path: '/v1/marketplace/catalog',
    requestSchema: MarketplaceCatalogRequestSchema,
    responseSchema: MarketplaceCatalogResponseSchema,
  },
  marketplaceInstall: {
    operation: 'marketplace.install.request',
    method: 'POST',
    path: '/v1/marketplace/install',
    requestSchema: MarketplaceInstallRequestSchema,
    responseSchema: MarketplaceInstallResponseSchema,
  },
  marketplaceInstallPlan: {
    operation: 'marketplace.install.plan',
    method: 'POST',
    path: '/v1/marketplace/install-plan',
    requestSchema: MarketplaceInstallPlanRequestSchema,
    responseSchema: MarketplaceInstallPlanResponseSchema,
  },
  marketplaceInstallationGet: {
    operation: 'marketplace.installation.get',
    method: 'POST',
    path: '/v1/marketplace/installations/get',
    requestSchema: MarketplaceInstallationGetRequestSchema,
    responseSchema: MarketplaceInstallationGetResponseSchema,
  },
  marketplaceInstallationUninstall: {
    operation: 'marketplace.installation.uninstall',
    method: 'POST',
    path: '/v1/marketplace/installations/uninstall',
    requestSchema: MarketplaceInstallationUninstallRequestSchema,
    responseSchema: MarketplaceInstallationUninstallResponseSchema,
  },
} as const)

export type ControlApiOperationName = keyof typeof ControlApiOperations
