import {
  GraphDefinitionPublishRequestSchema,
  GraphDefinitionDeprecationRequestSchema,
  GraphDefinitionRevocationRequestSchema,
  GraphDefinitionResolutionRequestSchema,
  GraphDefinitionResponseSchema,
  ExecutionCancellationCommandSchema,
  ExecutionCancellationCommandResultSchema,
  InteractionResponseCommandSchema,
  InteractionResponseCommandResultSchema,
  ContextPackageResolutionRequestSchema,
  ContextPackageResolutionResponseSchema,
  ExecutionAcceptanceRequestSchema,
  ExecutionAcceptanceResponseSchema,
  ExecutionRequestValidationRequestSchema,
  ExecutionRequestValidationResponseSchema,
  ProfileResolutionRequestSchema,
  ProfileResolutionResponseSchema,
  ProjectStateInitializationRequestSchema,
  ProjectStateInitializationResponseSchema,
  ProjectStateResolutionRequestSchema,
  ProjectStateResolutionResponseSchema,
  RuntimeListRequestSchema,
  RuntimeListResponseSchema,
  ServiceAuthenticationRequestSchema,
  ServiceAuthenticationResponseSchema,
  ExternalSessionGetRequestSchema,
  ExternalSessionGetResponseSchema,
  ExternalSessionListRequestSchema,
  ExternalSessionListResponseSchema,
  RuntimeConnectionGetRequestSchema,
  RuntimeConnectionGetResponseSchema,
  RuntimeConnectionListRequestSchema,
  RuntimeConnectionListResponseSchema,
  MarketplaceCatalogRequestSchema,
  MarketplaceCatalogResponseSchema,
  MarketplaceInstallPlanRequestSchema,
  MarketplaceInstallPlanResponseSchema,
  MarketplaceInstallRequestSchema,
  MarketplaceInstallResponseSchema,
  MarketplaceInstallationGetRequestSchema,
  MarketplaceInstallationGetResponseSchema,
  MarketplaceInstallationUninstallRequestSchema,
  MarketplaceInstallationUninstallResponseSchema,
} from '@control-plane/contracts'

export const ControlApiOperations = Object.freeze({
  publishGraph: {
    operation: 'graph.publish',
    method: 'POST',
    path: '/v1/graphs/publish',
    requestSchema: GraphDefinitionPublishRequestSchema,
    responseSchema: GraphDefinitionResponseSchema,
  },
  deprecateGraph: {
    operation: 'graph.deprecate',
    method: 'POST',
    path: '/v1/graphs/deprecate',
    requestSchema: GraphDefinitionDeprecationRequestSchema,
    responseSchema: GraphDefinitionResponseSchema,
  },
  revokeGraph: {
    operation: 'graph.revoke',
    method: 'POST',
    path: '/v1/graphs/revoke',
    requestSchema: GraphDefinitionRevocationRequestSchema,
    responseSchema: GraphDefinitionResponseSchema,
  },
  resolveGraph: {
    operation: 'graph.resolve',
    method: 'POST',
    path: '/v1/graphs/resolve',
    requestSchema: GraphDefinitionResolutionRequestSchema,
    responseSchema: GraphDefinitionResponseSchema,
  },
  cancelExecution: {
    responseStatus: 202,
    operation: 'execution.cancel',
    method: 'POST',
    path: '/v1/executions/cancel',
    requestSchema: ExecutionCancellationCommandSchema,
    responseSchema: ExecutionCancellationCommandResultSchema,
  },
  respondToInteraction: {
    responseStatus: 202,
    operation: 'interaction.respond',
    method: 'POST',
    path: '/v1/interactions/respond',
    requestSchema: InteractionResponseCommandSchema,
    responseSchema: InteractionResponseCommandResultSchema,
  },
  verifyAuthentication: {
    operation: 'authentication.verify',
    method: 'POST',
    path: '/v1/authentication/verify',
    requestSchema: ServiceAuthenticationRequestSchema,
    responseSchema: ServiceAuthenticationResponseSchema,
  },
  resolveProfile: {
    operation: 'profile.resolve',
    method: 'POST',
    path: '/v1/profiles/resolve',
    requestSchema: ProfileResolutionRequestSchema,
    responseSchema: ProfileResolutionResponseSchema,
  },
  resolveProjectState: {
    operation: 'project-state.resolve',
    method: 'POST',
    path: '/v1/project-states/resolve',
    requestSchema: ProjectStateResolutionRequestSchema,
    responseSchema: ProjectStateResolutionResponseSchema,
  },
  initializeProjectState: {
    operation: 'project-state.initialize',
    method: 'POST',
    path: '/v1/project-states/initialize',
    requestSchema: ProjectStateInitializationRequestSchema,
    responseSchema: ProjectStateInitializationResponseSchema,
  },
  resolveContextPackage: {
    operation: 'context-package.resolve',
    method: 'POST',
    path: '/v1/context-packages/resolve',
    requestSchema: ContextPackageResolutionRequestSchema,
    responseSchema: ContextPackageResolutionResponseSchema,
  },
  listRuntimes: {
    operation: 'runtime.list',
    method: 'POST',
    path: '/v1/runtimes/list',
    requestSchema: RuntimeListRequestSchema,
    responseSchema: RuntimeListResponseSchema,
  },
  listRuntimeConnections: {
    operation: 'runtime-connection.list',
    method: 'POST',
    path: '/v1/runtime-connections/list',
    requestSchema: RuntimeConnectionListRequestSchema,
    responseSchema: RuntimeConnectionListResponseSchema,
  },
  getRuntimeConnection: {
    operation: 'runtime-connection.get',
    method: 'POST',
    path: '/v1/runtime-connections/get',
    requestSchema: RuntimeConnectionGetRequestSchema,
    responseSchema: RuntimeConnectionGetResponseSchema,
  },
  listExternalSessions: {
    operation: 'external-session.list',
    method: 'POST',
    path: '/v1/external-sessions/list',
    requestSchema: ExternalSessionListRequestSchema,
    responseSchema: ExternalSessionListResponseSchema,
  },
  getExternalSession: {
    operation: 'external-session.get',
    method: 'POST',
    path: '/v1/external-sessions/get',
    requestSchema: ExternalSessionGetRequestSchema,
    responseSchema: ExternalSessionGetResponseSchema,
  },
  validateExecutionRequest: {
    operation: 'execution.validate',
    method: 'POST',
    path: '/v1/executions/validate',
    requestSchema: ExecutionRequestValidationRequestSchema,
    responseSchema: ExecutionRequestValidationResponseSchema,
  },
  acceptExecution: {
    operation: 'execution.accept',
    method: 'POST',
    path: '/v1/executions/accept',
    requestSchema: ExecutionAcceptanceRequestSchema,
    responseSchema: ExecutionAcceptanceResponseSchema,
  },
  marketplaceCatalog: {
    operation: 'marketplace.catalog.read',
    method: 'POST',
    path: '/v1/marketplace/catalog',
    requestSchema: MarketplaceCatalogRequestSchema,
    responseSchema: MarketplaceCatalogResponseSchema,
  },
  marketplaceInstall: {
    operation: 'marketplace.install.request',
    method: 'POST',
    path: '/v1/marketplace/install',
    requestSchema: MarketplaceInstallRequestSchema,
    responseSchema: MarketplaceInstallResponseSchema,
  },
  marketplaceInstallPlan: {
    operation: 'marketplace.install.plan',
    method: 'POST',
    path: '/v1/marketplace/install-plan',
    requestSchema: MarketplaceInstallPlanRequestSchema,
    responseSchema: MarketplaceInstallPlanResponseSchema,
  },
  marketplaceInstallationGet: {
    operation: 'marketplace.installation.get',
    method: 'POST',
    path: '/v1/marketplace/installations/get',
    requestSchema: MarketplaceInstallationGetRequestSchema,
    responseSchema: MarketplaceInstallationGetResponseSchema,
  },
  marketplaceInstallationUninstall: {
    operation: 'marketplace.installation.uninstall',
    method: 'POST',
    path: '/v1/marketplace/installations/uninstall',
    requestSchema: MarketplaceInstallationUninstallRequestSchema,
    responseSchema: MarketplaceInstallationUninstallResponseSchema,
  },
} as const)

export type ControlApiOperationName = keyof typeof ControlApiOperations
