import {
  InteractionResponseCommandSchema,
  InteractionResponseCommandResultSchema,
  ContextPackageResolutionRequestSchema,
  ContextPackageResolutionResponseSchema,
  ExecutionAcceptanceRequestSchema,
  ExecutionAcceptanceResponseSchema,
  ExecutionRequestValidationRequestSchema,
  ExecutionRequestValidationResponseSchema,
  ProfileResolutionRequestSchema,
  ProfileResolutionResponseSchema,
  ProjectStateResolutionRequestSchema,
  ProjectStateResolutionResponseSchema,
  RuntimeListRequestSchema,
  RuntimeListResponseSchema,
  ServiceAuthenticationRequestSchema,
  ServiceAuthenticationResponseSchema,
  ExternalSessionGetRequestSchema,
  ExternalSessionGetResponseSchema,
  ExternalSessionListRequestSchema,
  ExternalSessionListResponseSchema,
  RuntimeConnectionGetRequestSchema,
  RuntimeConnectionGetResponseSchema,
  RuntimeConnectionListRequestSchema,
  RuntimeConnectionListResponseSchema,
  MarketplaceCatalogRequestSchema,
  MarketplaceCatalogResponseSchema,
  MarketplaceInstallRequestSchema,
  MarketplaceInstallResponseSchema,
} from '@control-plane/contracts'

export const ControlApiOperations = Object.freeze({
  respondToInteraction: {
    responseStatus: 202,
    operation: 'interaction.respond',
    method: 'POST',
    path: '/v1/interactions/respond',
    requestSchema: InteractionResponseCommandSchema,
    responseSchema: InteractionResponseCommandResultSchema,
  },
  verifyAuthentication: {
    operation: 'authentication.verify',
    method: 'POST',
    path: '/v1/authentication/verify',
    requestSchema: ServiceAuthenticationRequestSchema,
    responseSchema: ServiceAuthenticationResponseSchema,
  },
  resolveProfile: {
    operation: 'profile.resolve',
    method: 'POST',
    path: '/v1/profiles/resolve',
    requestSchema: ProfileResolutionRequestSchema,
    responseSchema: ProfileResolutionResponseSchema,
  },
  resolveProjectState: {
    operation: 'project-state.resolve',
    method: 'POST',
    path: '/v1/project-states/resolve',
    requestSchema: ProjectStateResolutionRequestSchema,
    responseSchema: ProjectStateResolutionResponseSchema,
  },
  resolveContextPackage: {
    operation: 'context-package.resolve',
    method: 'POST',
    path: '/v1/context-packages/resolve',
    requestSchema: ContextPackageResolutionRequestSchema,
    responseSchema: ContextPackageResolutionResponseSchema,
  },
  listRuntimes: {
    operation: 'runtime.list',
    method: 'POST',
    path: '/v1/runtimes/list',
    requestSchema: RuntimeListRequestSchema,
    responseSchema: RuntimeListResponseSchema,
  },
  listRuntimeConnections: {
    operation: 'runtime-connection.list',
    method: 'POST',
    path: '/v1/runtime-connections/list',
    requestSchema: RuntimeConnectionListRequestSchema,
    responseSchema: RuntimeConnectionListResponseSchema,
  },
  getRuntimeConnection: {
    operation: 'runtime-connection.get',
    method: 'POST',
    path: '/v1/runtime-connections/get',
    requestSchema: RuntimeConnectionGetRequestSchema,
    responseSchema: RuntimeConnectionGetResponseSchema,
  },
  listExternalSessions: {
    operation: 'external-session.list',
    method: 'POST',
    path: '/v1/external-sessions/list',
    requestSchema: ExternalSessionListRequestSchema,
    responseSchema: ExternalSessionListResponseSchema,
  },
  getExternalSession: {
    operation: 'external-session.get',
    method: 'POST',
    path: '/v1/external-sessions/get',
    requestSchema: ExternalSessionGetRequestSchema,
    responseSchema: ExternalSessionGetResponseSchema,
  },
  validateExecutionRequest: {
    operation: 'execution.validate',
    method: 'POST',
    path: '/v1/executions/validate',
    requestSchema: ExecutionRequestValidationRequestSchema,
    responseSchema: ExecutionRequestValidationResponseSchema,
  },
  acceptExecution: {
    operation: 'execution.accept',
    method: 'POST',
    path: '/v1/executions/accept',
    requestSchema: ExecutionAcceptanceRequestSchema,
    responseSchema: ExecutionAcceptanceResponseSchema,
  },
  marketplaceCatalog: {
    operation: 'marketplace.catalog.read',
    method: 'POST',
    path: '/v1/marketplace/catalog',
    requestSchema: MarketplaceCatalogRequestSchema,
    responseSchema: MarketplaceCatalogResponseSchema,
  },
  marketplaceInstall: {
    operation: 'marketplace.install.request',
    method: 'POST',
    path: '/v1/marketplace/install',
    requestSchema: MarketplaceInstallRequestSchema,
    responseSchema: MarketplaceInstallResponseSchema,
  },
} as const)

export type ControlApiOperationName = keyof typeof ControlApiOperations
