ALTER TABLE "command_inbox" ALTER COLUMN "project_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "context_packages" ALTER COLUMN "project_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "execution_cancellations" ALTER COLUMN "project_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "execution_events" ALTER COLUMN "project_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "execution_plans" ALTER COLUMN "project_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "executions" ALTER COLUMN "project_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "command_inbox" ADD COLUMN "execution_scope" jsonb;--> statement-breakpoint
ALTER TABLE "context_packages" ADD COLUMN "execution_scope" jsonb;--> statement-breakpoint
ALTER TABLE "execution_cancellations" ADD COLUMN "execution_scope" jsonb;--> statement-breakpoint
ALTER TABLE "execution_events" ADD COLUMN "execution_scope" jsonb;--> statement-breakpoint
ALTER TABLE "execution_plans" ADD COLUMN "execution_scope" jsonb;--> statement-breakpoint
ALTER TABLE "executions" ADD COLUMN "execution_scope" jsonb;--> statement-breakpoint
CREATE UNIQUE INDEX "command_inbox_workspace_idempotency_unique" ON "command_inbox" USING btree ("caller_principal_id","operation","workspace_id","idempotency_key") WHERE "command_inbox"."project_id" is null;--> statement-breakpoint
ALTER TABLE "command_inbox" ADD CONSTRAINT "command_inbox_scope_check" CHECK ((("command_inbox"."execution_scope" is null and "command_inbox"."project_id" is not null) or ("command_inbox"."project_id" is null and "command_inbox"."execution_scope" = '{"schemaVersion":1,"kind":"workspace"}'::jsonb) or ("command_inbox"."project_id" is not null and "command_inbox"."execution_scope" = jsonb_build_object('schemaVersion', 1, 'kind', 'project', 'projectId', "command_inbox"."project_id"))) is true);--> statement-breakpoint
ALTER TABLE "context_packages" ADD CONSTRAINT "context_packages_scope_check" CHECK ((("context_packages"."execution_scope" is null and "context_packages"."project_id" is not null) or ("context_packages"."project_id" is null and "context_packages"."execution_scope" = '{"schemaVersion":1,"kind":"workspace"}'::jsonb) or ("context_packages"."project_id" is not null and "context_packages"."execution_scope" = jsonb_build_object('schemaVersion', 1, 'kind', 'project', 'projectId', "context_packages"."project_id"))) is true);--> statement-breakpoint
ALTER TABLE "execution_cancellations" ADD CONSTRAINT "execution_cancellations_scope_check" CHECK ((("execution_cancellations"."execution_scope" is null and "execution_cancellations"."project_id" is not null) or ("execution_cancellations"."project_id" is null and "execution_cancellations"."execution_scope" = '{"schemaVersion":1,"kind":"workspace"}'::jsonb) or ("execution_cancellations"."project_id" is not null and "execution_cancellations"."execution_scope" = jsonb_build_object('schemaVersion', 1, 'kind', 'project', 'projectId', "execution_cancellations"."project_id"))) is true);--> statement-breakpoint
ALTER TABLE "execution_events" ADD CONSTRAINT "execution_events_scope_check" CHECK ((("execution_events"."execution_scope" is null and "execution_events"."project_id" is not null) or ("execution_events"."project_id" is null and "execution_events"."execution_scope" = '{"schemaVersion":1,"kind":"workspace"}'::jsonb) or ("execution_events"."project_id" is not null and "execution_events"."execution_scope" = jsonb_build_object('schemaVersion', 1, 'kind', 'project', 'projectId', "execution_events"."project_id"))) is true);--> statement-breakpoint
ALTER TABLE "execution_plans" ADD CONSTRAINT "execution_plans_scope_check" CHECK ((("execution_plans"."execution_scope" is null and "execution_plans"."project_id" is not null) or ("execution_plans"."project_id" is null and "execution_plans"."execution_scope" = '{"schemaVersion":1,"kind":"workspace"}'::jsonb) or ("execution_plans"."project_id" is not null and "execution_plans"."execution_scope" = jsonb_build_object('schemaVersion', 1, 'kind', 'project', 'projectId', "execution_plans"."project_id"))) is true);--> statement-breakpoint
ALTER TABLE "executions" ADD CONSTRAINT "executions_scope_check" CHECK ((("executions"."execution_scope" is null and "executions"."project_id" is not null) or ("executions"."project_id" is null and "executions"."execution_scope" = '{"schemaVersion":1,"kind":"workspace"}'::jsonb) or ("executions"."project_id" is not null and "executions"."execution_scope" = jsonb_build_object('schemaVersion', 1, 'kind', 'project', 'projectId', "executions"."project_id"))) is true);